add one more jack
kevin940726/dailyjack pull request #13
Opened 2017-11-16 05:26 UTC by escapiststupor

單純是練習一下往upstream發pr的功能怎麼用

2017-11-19 16:15 UTC, kevin940726 requested changes

2017-11-19 16:15 UTC, kevin940726 commented on packages/dailyjack-core/jacks.json
> +]
Please preserve the end-of-file line.

2017-11-19 16:15 UTC, kevin940726 commented on packages/dailyjack-core/jacks.json
> +    "author": "不是我",
Please acknowledge yourself.

2017-11-19 16:15 UTC, kevin940726 commented on packages/dailyjack-core/jacks.json
> +    "isLimited": true
This is not a limited jack.

2017-11-19 23:46 UTC, escapiststupor commented on packages/dailyjack-core/jacks.json
> +    "author": "不是我",
會不會被吉QQ

2017-11-19 23:46 UTC, escapiststupor commented on packages/dailyjack-core/jacks.json
> +    "isLimited": true
limited Jack會發生什麼事

2017-11-20 00:01 UTC, escapiststupor commented on packages/dailyjack-core/jacks.json
> +    "isLimited": true
我懂了....

2017-11-20 07:46 UTC, kevin940726 commented on packages/dailyjack-core/jacks.json
> +    "author": "不是我",
Don't worry 😂

2017-11-22 03:43 UTC, kevin940726 approved these changes

2017-11-22 03:43 UTC, merged